NSS-Day-Cohort-66/rare-client-rare-poultry

src/pages/Login.jsx
src/pages/Register.jsx

#Nomenclature changed from username to email
Client is now sending `email` in authentication packet

Nomenclature changed to email from username

---

src/components/ApplicationViews.jsx
src/components/Categories.jsx
src/services/categoryService.jsx

Basic list rendering without styling as per ticket. 
Make sure that the page is showing: 
Categories
Funny
Lifestyle

Categories component created

---

src/components/ApplicationViews.jsx
src/components/Posts.jsx
src/services/postService.jsx

Created Posts component so posts will list in app
Created postService to fetch posts from the API
Added routing pathways for Posts so NavBar will be responsive

Posts component and routing and service

---

src/components/Posts.jsx

Made small alterations to the return in the Post component so the correct info populates in React

Altered the Post component to show correct info

---

src/components/ApplicationViews.jsx
src/components/Navbar.jsx
src/components/Users.jsx
src/services/userService.jsx

- ```git fetch``` branch ```jrm-ViewUsersClient```
- run ```npm run dev``` in terminal
- check out new User Profiles view

Jrm view users client

---

src/components/Tags.jsx
src/services/tagService.jsx

- Created an `addTag` function to POST new items to `/tags`
- Added a tag form to capture user input for adding new tags
- Fetch and check out the `nc-tag-post-client` branch
- Run `npm run dev` if you haven't already
- Navigate to the tag manager on the nav bar
- Fill out the form and click `save tag`
- You should see the tag added to the list of tags

Client now able to add tags in tag manager

---

src/components/ApplicationViews.jsx
src/components/Comments.jsx
src/services/commentsService.jsx
src/services/postService.jsx

1. Make sure you have the latest api main pulled down
2. git fetch
3. git checkout pmPostComments
4. npm run dev
5. visit http://localhost:3000/comments
6. You should see comment content, date created and author
* Correct Route cannot be completed until after Post Details is created
* useParams will be used in the Comments.jsx module

Pm post comments

---

src/components/ApplicationViews.jsx
src/components/PostDetails.jsx
src/components/Posts.jsx

PostDetails component so when a post is clicked on in All Posts, a new page pops up with the post details
Updated Posts.jsx to now include a clickable link on the post title
Updated routing so the new page will load properly with the post details
Make sure API is running. Click on All Posts. When the posts appear, click on the title of the post. A new page should load with a list of 5 details (Post title, image, content, publication date, and author's name)

Changes to make post details visible

---

src/components/ApplicationViews.jsx
src/components/UserDetails.jsx
src/components/Users.jsx
src/services/userService.jsx

- ```git fetch``` branch ```jrm-UserDetailsClient```
- ```npm run dev```
- Click on User Profiles in navbar
- You should see that user's info
- **NOTE: if you don't see profile image, username, etc. check to see if that info is in your database.

Jrm user details client

---

src/components/PostDetails.jsx
src/components/Posts.jsx

Due to changes made to PostSerializer and Post model, had to update code for Posts and PostDetails components so those will still show up
Added some simple styling to Posts and PostDetails
Make sure API is running. Click on All Posts. The posts should appear, then click on the title of the post. A new page should load with a list of 5 details (Post title, image, content, publication date, and author's name)

Updated Post and PostDetails and added simple styling

---

src/components/ApplicationViews.jsx
src/components/UserPosts.jsx

* Given the user is in the Rare application
When they select the My Posts menu option
Then they should be directed to the "My Posts" list page
* And the page should display ALL the Posts authored by the logged-in user
And each post in the list should display the title, author and category
* Should be ordered by date created with the most recent at the top
1. git fetch
2. git checkout pm-user-posts
3. npm run dev
4. navigate to my posts to see if the post is there
5. Check to see if the user.id is equal to the honey_user in local storage
6. Check the database to see if all posts related to that user are showing up

PM User Posts

---

src/components/Categories.jsx
src/components/Tags.jsx

- Applied styling from the `Tags.jsx` component
- Created `changeCategory()` to handle PUT requests to `http://localhost:8000/categories/${id}`
- Added modal structure from `Tags.jsx` component

Styling for Categories, Edit & Delete modal framework built

---

src/components/CreatePost.jsx
src/components/Posts.jsx
src/components/UserPosts.jsx

Styling for New Post, All Posts, and My Posts

---

src/components/Categories.jsx

#Delete Category in Category Manager 
##Steps to Test
1. Git fetch
2. git checkout PMdeleteCat
3. npm run dev
4. Navigate to the category manager tab
5. delete a category
6. It should not appear anymore and should be deleted from the database

created delete category functionality and styled modal

---

src/components/Comments.jsx

- Fetch and checkout the `nc-comment-edit` branch
- Navigate to a post that has comments
- Click the edit button on a comment
- In the modal that pops up, edit the name and click save.
- Ensure the comment was updated properly

Edit Comment functioning through modals

---

src/components/AddComments.jsx
src/components/ApplicationViews.jsx
src/components/PostDetails.jsx

Given the user is viewing the Details of a Post
When they select the Add Comment menu option
Then they should be directed to a page with a form for creating a new Comment
Given the user has entered in the comment text
When they click the Save button
Then the Comment should be saved to the database
And the creation datetime should be automatically set to the current date and time
And the user should be redirected to the new Comments list page for the related Post
1. git fetch
2. git checkout PMcreate-comment
3. npm run dev
4. Navigate to any post detail
5. at the bottom of the page, click add a comment 
6. Fill out the content
7. hit submit
8. It should not appear as a comment
9. Double check your database

add a comment functionality added

---

src/components/Posts.jsx

A delete button is now present under all posts
A Modal will pop up asking if you are sure you want to delete
If you are not the author of the post, you will not be able to delete if you try and click OK
(Side note: also made a change to API which will also have to be pulled before this works, that change makes sure only the current user can delete their own post)

Sc client post delete

---

src/components/Posts.jsx

added condition for delete button

---

src/components/EditPost.jsx

This is just for the EditPosts.jsx, I am pushing this early so Justin can work on it incorporating the tags as it was the only part I didn't have in my original scope.

created EditPost module

---

src/components/Comments.jsx
src/components/PostDetails.jsx

- ```git fetch``` branch ```jrm-removetagsclient1```
- ```npm run dev```
- Try to delete a comment from any post, or create a comment first
- After clicking "ok" in the modal, page should refresh and only that comment should be removed
- Open network tab in dev tools and make sure you received response code of 204 No Content after the DELETE request
- And a 200 Ok after the GET request

Updated Comments.jsx
